const setConfig = ()=>{
    return {
        baseUrl: '/diradmin/athletes',
        baseUrlCreate: '/diradmin/athletes/create',
        baseUrlDelete: 'athletes.destroy',
        title: 'Athletes',
        titleSingle: 'Athlete',
        url: 'athletes.store',
        method: 'post',
        typeForm: 'Create',
        resource: {
            name: '',
            last_name: '',
            box: '',
            image: '',
            category_id: null,
            dpi: '',
            sex: '',
            date_of_birth: '',
            phone: '',
            email: '',
            name_contact_emergency: '',
            phone_contact_emergency: '',
            shirt_size: ''
        },
        fields: [
          {
            name: 'name',
            label: 'Name',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Name',
          },
          {
            name: 'last_name',
            label: 'Last Name',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Last Name',
          },
          {
            name: 'box',
            label: 'Box',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Box',
          },
          {
            name: 'image',
            label: 'Image',
            type: 'file',
            typeField: 'file',
            required: true,
            placeholder: 'Image',
          },
          {
            name: 'category_id',
            label: 'Category',
            url: '/only/categories',
            type: 'name',
            labelShow: 'category_name',
            typeField: 'select',
            required: true,
            placeholder: 'Category',
          },
          {
            name: 'dpi',
            label: 'Dpi',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Dpi',
          },
          {
            name: 'email',
            label: 'Email',
            type: 'email',
            typeField: 'input',
            required: true,
            placeholder: 'Email',
          },
          {
            name: 'date_of_birth',
            label: 'Fecha de nacimiento',
            type: 'date',
            typeField: 'input',
            required: true,
            placeholder: '',
          },
          {
            name: 'phone',
            label: 'Número de telefono',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Número de telefono',
          },
          {
            name: 'name_contact_emergency',
            label: 'Nombre de contacto de emergencia',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Nombre de contacto de emergencia',
          },
          {
            name: 'phone_contact_emergency',
            label: 'Número de contacto de emergencia',
            type: 'text',
            typeField: 'input',
            required: true,
            placeholder: 'Número de contacto de emergencia',
          },
          {
            name: 'sex',
            label: 'Sexo',
            type: 'text',
            typeField: 'radio',
            options: [
              { label: 'F', value: 'F' },
              { label: 'M', value: 'M' },
            ],
            required: true,
            placeholder: 'Sexo',
          },
          {
            name: 'shirt_size',
            label: 'Talla de playera',
            type: 'text',
            typeField: 'radio',
            options: [
              { label: 'S', value: 'S' },
              { label: 'M', value: 'M' },
              { label: 'L', value: 'L' },
              { label: 'XL', value: 'XL' },
            ],
            required: true,
            placeholder: 'Talla de playera',
          },
        ],
      }
}

export default setConfig